Repository ramses-organisation/ramses, pull requests merged in 2025-08, with the labels that each got.

#178 further document the order of hydro variables
  doc/dev_docs/implementation.md
  hydro/hydro_parameters.f90
  hydro/read_hydro_params.f90
  mhd/hydro_parameters.f90
Labels: documentation, run tests

#174 combine the hydro and mhd versions of init_flow_fine.f90 into one
  hydro/init_flow_fine.f90
  mhd/init_flow_fine.f90
Labels: code quality, run tests, SPACE

#180 Updated patch files to reflect changes in main code
  patch/mhd/coeur/cooling_fine.f90
  patch/mhd/coeur/hydro_parameters.f90
  patch/mhd/coeur/read_hydro_params.f90
  rt/rt_flux_module.f90
Labels: run tests

#140 Optimized the creation of cloud particles
  amr/load_balance.f90
  pm/pm_parameters.f90
  pm/sink_particle.f90
Labels: run tests, performance

#169 change slope_type in imhd-tube and imhd-tube-nener tests
  tests/mhd/imhd-tube-nener/imhd-tube-nener-ref.dat
  tests/mhd/imhd-tube-nener/imhd-tube-nener.nml
  tests/mhd/imhd-tube/imhd-tube-ref.dat
  tests/mhd/imhd-tube/imhd-tube.nml
Labels: CI

#158 Optimize ctoprim
  hydro/umuscl.f90
  hydro/uplmde.f90
Labels: run tests, SPACE, performance

#184 Combine hydro, mhd and rhd versions of hydro_parameters.f90
  hydro/hydro_parameters.f90
  mhd/hydro_parameters.f90
  rhd/README
  rhd/condinit.f90
  rhd/godunov_utils.f90
  rhd/hydro_parameters.f90
  rhd/init_flow_fine.f90
  rhd/init_hydro.f90
  rhd/interpol_hydro.f90
  rhd/output_hydro.f90
  rhd/read_hydro_params.f90
  rhd/test_suite/jet/read_hydro_params.f90
  rhd/umuscl.f90
  rhd/uplmde.f90
  rhd/write_screen.f90
Labels: code quality, run tests

#183 Combine hydro and mhd versions of output_hydro.f90
  hydro/output_hydro.f90
  mhd/output_hydro.f90
Labels: code quality, run tests, SPACE

#154 Refactor and optimize uslope
  bin/Makefile
  hydro/hydro_parameters.f90
  hydro/slope_types.f90
  hydro/umuscl.f90
  mhd/umuscl.f90
Labels: code quality, run tests, SPACE, performance, hydro solver rewrite
