Repository ramses-organisation/ramses, pull requests merged in 2025-06, with the labels that each got.

#119 OpenMP: hydro on unigrid
  hydro/courant_fine.f90
  hydro/godunov_fine.f90
  hydro/interpol_hydro.f90
Labels: openmp, SPACE

#117 Remove hard cast of idp to short int
  pm/particle_tree.f90
Labels: bug, run tests

#132 [tests] Added a check for the clumpfinder
  tests/poisson/cosmo/after-test.sh
  tests/poisson/cosmo/clump-ref.txt
  tests/poisson/cosmo/cosmo-ref.dat
  tests/poisson/cosmo/cosmo.nml
  tests/poisson/cosmo/plot-cosmo.py
Labels: test case, run tests

#144 Remove references to the stable branch in the doc
  .github/pull_request_template.md
  README.md
  doc/dev_docs/developer_guide.md
Labels: documentation
